version: "2"
run:
  timeout: 10m
  modules-download-mode: readonly

output:
  formats:
    tab:
      path: stderr

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - errname
    - godot
    - misspell
    - noctx
    - revive
    - unconvert
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: strict
