name: actionlint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"
          cache: true

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install Actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: Run Actionlint
        run: actionlint
