name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true

      - name: Setup nix
        uses: cachix/install-nix-action@v30

      - name: Build
        run: go build -o hmnb .

      - name: Update flake
        run: nix flake update

      - name: Build news
        run: |
          nix build .#homeConfigurations.a.config.news.json.output
          cp result news.json

      - name: Run
        env:
          HMNB_PATH: result
          HMNB_MAX_POSTS: 2
          HMNB_MASTODON_SERVER: https://techhub.social/
          HMNB_MASTODON_CLIENT_ID: ${{ secrets.HMNB_MASTODON_CLIENT_ID }}
          HMNB_MASTODON_CLIENT_SECRET: ${{ secrets.HMNB_MASTODON_CLIENT_SECRET }}
          HMNB_MASTODON_ACCESS_TOKEN: ${{ secrets.HMNB_MASTODON_ACCESS_TOKEN }}
        run: ./hmnb

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: |
            news.json
            mastodon.json
