name: go-tidy-check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  tidycheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"
          cache: true

      - name: Check if go.mod and go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
