name: unit-tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true

      - name: Go test
        run: go test -v ./...
